### PR TITLE
Add osx-arm64 support

### PR DESCRIPTION
**Pull request by beenje**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beenje** [comment]
@conda-forge-admin, please rerender

**Comment by beenje** [comment]
@dlacoste-esrf I wanted to rebuild this version of pogo to add osx-arm64 support but it'f failing with:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project Pogo: Compilation failure
[ERROR] $SRC_DIR/org.tango.pogo.pogo_gui/src/existingcode/Activator.java:[9,8] cannot access org.eclipse.core.runtime.Plugin
[ERROR]   bad class file: /home/conda/.m2/repository/org/eclipse/platform/org.eclipse.core.runtime/3.27.0/org.eclipse.core.runtime-3.27.0.jar(/org/eclipse/core/runtime/Plugin.class)
[ERROR]     class file has wrong version 61.0, should be 55.0
```

Are you planning to move to java 17?
I know that [ATK](https://gitlab.com/tango-controls/atk) already did.
I had to rebuild jive for java >=17.

**Comment by dlacoste-esrf** [comment]
Yep it's planned, but it's not so easy… Our main dependency xtend/xtext need to be updated to the latest version for this, but since we didn't follow the updates, it's not straight forward (there is an API change, major one…). I worked on it at some point, so I have a working version but I have to merge the latest stuff and so on… Quite some work… I'll do it at some point, probably this summer…

**Comment by beenje** [comment]
OK, thanks. No worry. Nothing urgent. I'll close this.
We can add osx-arm64 support when there is a new version ready.

**Pull request closed without merging**
